### ISSUE TITLE
Compatibility with Java 9?

### ISSUE THREAD

**Issue by vo2maxCoding** [sosna/pinetrail#37]
Hello, I wanted to try pinetrail cli but stumbled from error to error.

1) there was a problem with gradle-2.2:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.4'.

--> I could fix this by upgrading to gradle-4.9

2) there was a problem with missing sonar-plugin: 

A problem occurred evaluating root project 'Pinetrail'.
> Plugin with id 'sonar-runner' not found.

--> I could fix this by removing sonar from the build.gradle

3) A new error in pinetrail-cli/cli.gradle line 1:

* What went wrong:
A problem occurred evaluating project ':pinetrail-cli'.
> Failed to apply plugin [class 'com.github.jengelman.gradle.plugins.shadow.ShadowJavaPlugin']
   > Could not create task of type 'ShadowJar'.

--> How to fix this?

**Comment by sosna** [comment]
Thanks for reporting this. 

Indeed, my systems still run Java 8 and I have not yet tried running the software with Java 9. Compatibility with Java 9 is on my list of things to investigate but I have very little time at the moment :(.

A possible workaround would be if you have the option of using Java 8, in addition to your current Java 9 setup, and point to it for pinetrail instead.

If this is not an option, then, from what you described, I guess you followed the [installation instructions](https://github.com/sosna/pinetrail/blob/master/INSTALL.md) but Graddle 2.2 failed to recognize Java 9, right? If so, which graddle command did you run next that led to the latest plugin issue?

**Comment by sosna** [comment]
I do have a fix on my local repo, and I'll push it to GH after having done some additional modifications. In a nutshell, there was an [incompatibility between Gradle and shadowjar](https://stackoverflow.com/questions/35343589/could-not-create-task-of-type-shadowjar) at some point, and this requires an upgrade of shadowjar to version 1.2.3. I upgraded it to the latest version (2.0.4) and it now works nicely.

**Comment by sosna** [comment]
I have released a new version and the problem should be fixed (i.e. it runs with Java 9).

In a nutshell:
- Java 9 required using a newer version of Gradle
- Versions of Gradle compatible with Java 9 required to update the shadowjar dependency
- In addition, the `installApp` command was dropped by Gradle in favour of `installDist`

**Comment by vo2maxCoding** [comment]
Great! Thank you for the quick response and fix!
